vmware-tanzu/velero-plugin-for-csi

- Dockerfile
Fix: #11 
Signed-off-by: Chin-Ya Huang <chin-ya.huang@suse.com>
> Change Dockerfile group to nogroup

- README.md
Command in README is no longer valid, updated.
Signed-off-by: Chin-Ya Huang <chin-ya.huang@suse.com>
> Update deploy driver command in README

- velero-csi-plugin/util_test.go
> Refactor unit tests to generate more verbose output

- go.mod
- go.sum
- velero-csi-plugin/csi_snapshotter.go
> 🏃‍♂️Use GR from velero kuberesource

- velero-csi-plugin/util.go
- velero-csi-plugin/util_test.go
- velero-csi-plugin/volumesnapshot_restorer.go
- velero-csi-plugin/volumesnapshotcontents_restorer.go
> Add copyright boilerplate

- velero-csi-plugin/csi_restorer.go
- velero-csi-plugin/csi_snapshotter.go
- velero-csi-plugin/csi_snapshotter_test.go
> Refactor setting annotations and labels on backed-pvc

- go.mod
- velero-csi-plugin/csi_restorer_test.go
- velero-csi-plugin/csi_snapshotter_test.go
- velero-csi-plugin/util_test.go
- velero-csi-plugin/volumesnapshot_restorer_test.go
- velero-csi-plugin/volumesnapshotcontents_restorer_test.go
> 🏃‍♀️Use stretchr

- Makefile
- hack/build.sh
- internal/backup/csi_snapshotter.go
- internal/backup/csi_snapshotter_test.go
- internal/restore/csi_restorer.go
- internal/restore/csi_restorer_test.go
- internal/restore/volumesnapshot_restorer.go
- internal/restore/volumesnapshot_restorer_test.go
- internal/restore/volumesnapshotcontents_restorer.go
- internal/restore/volumesnapshotcontents_restorer_test.go
- internal/util/labels_annotations.go
- internal/util/util.go
- internal/util/util_test.go
- main.go
> Repo re-org

- Makefile
> Add building container image to ci

- internal/backup/csi_snapshotter.go
- internal/util/util.go
Signed-off-by: Ashish Amarnath ashisham@vmware.com
> minor refactor to allow reuse

- .gitignore
Signed-off-by: Steve Kriss <krisss@vmware.com>
> add velero-plugin-for-csi binary to .gitignore

- internal/util/util.go
> Add clarifying comments

- internal/backup/volumesnapshot_action.go
- internal/restore/volumesnapshot_action.go
- internal/util/labels_annotations.go
> Save and use DeletionPolicy from backed up VolumeSnapshot during restore

- internal/backup/volumesnapshot_action.go
> add velero backup label for vsc created in vs backup item action

- internal/backup/pvc_action.go
- internal/backup/volumesnapshot_action.go
- internal/util/util.go
> Use GetValidName for label values

- README.md
> 📖 Update CSI plugin ReadMe

- .github/workflows/go.yml
- Makefile
> Setting up gh actions for image build and push

- internal/restore/volumesnapshot_action.go
> 🏃‍♂️ Add restore label on VSC created for static binding

- README.md
> 📖 add dockerhub link to docs

- .github/workflows/go.yml
- README.md
> Add build status badge to readme

- .github/workflows/go.yml
- README.md
Signed-off-by: Nolan Brubaker <brubakern@vmware.com>
> Address insensitive language

- internal/restore/volumesnapshot_action.go
- internal/util/util.go
- internal/util/util_test.go
Fixes: #41 
This PR should be merged after #63
> Skip static linking VSC creation if VS already exists

- internal/backup/pvc_action.go
Signed-off-by: JenTing Hsiao <jenting.hsiao@suse.com>
> fix warning message format

- README.md
- changelogs/CHANGELOG-0.1.2.md
> Add changelog and compatability table for v0.1.2

- Makefile
- hack/release-tools/changelog.sh
Signed-off-by: Nolan Brubaker <brubakern@vmware.com>
> Add changelog scripts and make target

- README.md
Signed-off-by: Dave Smith-Uchida <dsmithuchida@vmware.com>
> Added warning about CSI snapshot durability to README

- README.md
> Update README with new issue filing process.

- changelogs/unreleased/82-sshende-catalogicsoftware
PR #82 was merged without a change log. Adding one in this PR.
> add changelog for PR 82

- README.md
- go.sum
- internal/delete/volumesnapshot_action.go
- internal/delete/volumesnapshotcontent_action.go
- internal/util/util.go
- internal/util/util_test.go
- main.go
This change is incompatible with velero release `> v1.4 and <=v1.6`
Fixes #https://github.com/vmware-tanzu/velero/issues/3733
> ✨ ⚠️ DeleteItemAction for volumesnapshots and volumesnapshotcontents

- Dockerfile
Signed-off-by: Wenkai Yin(尹文开) <yinw@vmware.com>
> Change the base image to distroless

- README.md
- changelogs/CHANGELOG-0.2.0.md
- changelogs/unreleased/82-sshende-catalogicsoftware
- changelogs/unreleased/89-tomob
Signed-off-by: Wenkai Yin(尹文开) <yinw@vmware.com>
> Update the documents for the release 0.2.0

- .github/auto-assignees.yml
- .github/workflows/push.yml
- hack/docker-push.sh
Enable building and pushing image for release branches
Signed-off-by: Wenkai Yin(尹文开) <yinw@vmware.com>
> Enable building and pushing image for release branches

- README.md
Signed-off-by: JenTing Hsiao <jenting.hsiao@suse.com>
> Add CSI plugin compatible Velero version v1.8.x

- internal/backup/volumesnapshotcontent_action.go
Signed-off-by: Yuval Manor <yuvalman958@gmail.com>
> fix: VolumeSnapshotContentBackupItemAction AppliesTo() debug message

- internal/delete/volumesnapshotcontent_action.go
fix https://github.com/vmware-tanzu/velero/issues/4764
> Fix: Record a warning when deleting VSC but fail with NotFound.

- .github/auto-assignees.yml
Signed-off-by: Scott Seago <sseago@redhat.com>
> Added shubham to auto-assignees

- changelogs/unreleased/108-jxun
- internal/restore/volumesnapshot_action.go
Fix issue https://github.com/vmware-tanzu/velero/issues/4945
> Update VSC's DeletionPolicy to Retain when it is set to Delete.

- README.md
- changelogs/unreleased/108-jxun
- changelogs/unreleased/91-jxun
- changelogs/unreleased/99-reasonerjt
> Update document and changelog for v0.3.0

- changelogs/CHANGELOG-0.3.0.md
> Add changelog.

- README.md
> Add verified environment information.

- .github/workflows/pr.yml
- .github/workflows/push.yml
- Makefile
- changelogs/CHANGELOG-0.3.1.md
> Bump up Golang version to v1.17.13

- changelogs/unreleased/123-blackpiglet
- internal/backup/pvc_action.go
- internal/backup/volumesnapshot_action.go
- internal/backup/volumesnapshotclass_action.go
- internal/backup/volumesnapshotcontent_action.go
- internal/util/labels_annotations.go
Fix issue https://github.com/vmware-tanzu/velero/issues/5430.
> Support annotation "backup.velero.io/must-include-additional-items".

- changelogs/unreleased/125-blackpiglet
- internal/backup/pvc_action.go
- internal/backup/volumesnapshot_action.go
- internal/backup/volumesnapshotclass_action.go
- internal/backup/volumesnapshotcontent_action.go
- internal/util/labels_annotations.go
Fix issue https://github.com/vmware-tanzu/velero/issues/5430.
> [cherry-pick] Support annotation "backup.velero.io/must-include-additional-items".

- changelogs/CHANGELOG-0.3.2.md
> Add CHANGELOG for v0.3.2.

- changelogs/CHANGELOG-0.3.2.md
- changelogs/unreleased/125-blackpiglet
- changelogs/unreleased/126-blackpiglet
- changelogs/unreleased/129-blackpiglet
> Add v0.3.2 change log.

- Dockerfile
- changelogs/CHANGELOG-0.3.2.md
> Bump up busybox version to v1.35.0

- Dockerfile
- changelogs/CHANGELOG-0.3.2.md
> Bump up busybox version to v1.34.1

- Dockerfile
- changelogs/unreleased/133-blackpiglet
> Bump up busybox version to v1.34.1 for main.

- changelogs/CHANGELOG-0.4.0.md
- changelogs/unreleased/121-blackpiglet
- changelogs/unreleased/123-blackpiglet
- changelogs/unreleased/124-blackpiglet
- changelogs/unreleased/133-blackpiglet
> Add release-0.4 changelog.

- README.md
> Modify README file.

- .github/workflows/pr.yml
- .github/workflows/push.yml
- Makefile
> Pin Golang version to v1.18.8

- changelogs/unreleased/130-anshulahuja98
- internal/util/util.go
Fixes: https://github.com/vmware-tanzu/velero/issues/5566
> Log error message in CSI VSC when in error state

- Dockerfile
- changelogs/unreleased/142-blackpiglet
> Use ucblic busybox instead of glibc.

- internal/restore/pvc_action.go
- internal/restore/volumesnapshot_action.go
- internal/restore/volumesnapshotclass_action.go
- internal/restore/volumesnapshotcontent_action.go
Fixes https://github.com/vmware-tanzu/velero/issues/5527
> Honour restorePV flag in restore flow

- .github/workflows/pr.yml
- .github/workflows/push.yml
- Makefile
> Bump up Golang version to v1.18.10

- .github/workflows/pr.yml
- .github/workflows/push.yml
- Makefile
- README.md
Update the compatibility box in README.
Bump Golang version to v1.20.3.
> [release-0.5]Update compatibility box and bump Golang version.

- internal/backup/pvc_action.go
Fixes https://github.com/vmware-tanzu/velero/issues/6294
> Copy PVC labels to it's VolumeSnapshot 

- go.mod
- go.sum
- internal/backup/pvc_action_test.go
- internal/restore/pvc_action.go
- internal/restore/volumesnapshot_action.go
- internal/restore/volumesnapshotclass_action.go
- internal/restore/volumesnapshotcontent_action.go
- internal/util/labels_annotations.go
- main.go
> Fix 6117: add DataUploadResult ConfigMap retrieving and deleting code.

- internal/backup/pvc_action.go
- internal/backup/pvc_action_test.go
- internal/restore/pvc_action.go
- internal/restore/pvc_action_test.go
Fix issue https://github.com/vmware-tanzu/velero/issues/6574
> Check whether the PVC exists in RIA.

- README.md
Doc changes for https://github.com/vmware-tanzu/velero-plugin-for-csi/pull/193
> Fix the multiple vsc docs in readme

- internal/util/util.go
Fix issue https://github.com/vmware-tanzu/velero/issues/7251
> Fix panic when csi timeout duration is short
