vmware-tanzu/velero-plugin-for-csi

- velero-csi-plugin/util.go
- velero-csi-plugin/util_test.go
Signed-off-by: Steve Kriss <krisss@vmware.com>
Hopefully the comment explains why this is needed. For now I just reused the existing "wait" pattern from that func, though we'll need to add timeouts and maybe make some other changes to handle snapshot failures later too.
> wait for VolumeSnapshotContents to have a snapshot handle during backup

- internal/backup/csi_snapshotter.go
Velero core will query for VolumeSnapshots with the backup name, which
can't be done against an annotation, so put the backup name as a label
instead.
Prerequisite for https://github.com/vmware-tanzu/velero/pull/2323
Signed-off-by: Nolan Brubaker <brubakern@vmware.com>
> Label created VolumeSnapshots with the backup name

- internal/backup/volumesnapshot_action.go
- internal/restore/pvc_action.go
- internal/restore/pvc_action_test.go
- internal/util/labels_annotations.go
Fixes #40 
While restoring a PVC, set the storage resource request of the PVC to the larger of the PVC's storage resource requests and the restore size of the volume snapshot.
> Set PVC storage requests if restore size is greater

- internal/restore/pvc_action.go
- internal/restore/volumesnapshot_action.go
- Check for presence of namespace mapping specification during Restore.
- If there is a valid mapping found, then, replace the original namespace in VolumeSnapshot and PVC Objects to the mapped namespace before restoring these objects.
- Fixes PR 2143(https://github.com/vmware-tanzu/velero/issues/2143)
- [TestResults.txt](https://github.com/vmware-tanzu/velero-plugin-for-csi/files/5672901/TestResults.txt)
Signed-off-by: Swanand Shende from Catalogic Software <sshende@catalogicsoftware.com>
> Allow cross-namespace restore of PVC's with CSI volumes

- changelogs/unreleased/89-tomob
- internal/restore/pvc_action.go
- internal/restore/pvc_action_test.go
PVCs can have any number annotations used for any purposes. Removing
them all can brake clients' workflows.
This commit changes the removal to only remove the annotations that are
used by K8s itself to manage PVC-PV binding. All other annotations are
left intact.
Fixes [issue #3925](https://github.com/vmware-tanzu/velero/issues/3925)
Signed-off-by: Tomasz Baranski <tbaransk@redhat.com>
> Only remove annotations related to PV binding

- changelogs/unreleased/100-jxun
- internal/util/util.go
- internal/util/util_test.go
fix https://github.com/vmware-tanzu/velero/issues/4819
> Add ReadyToUse status check before assuming VolumeSnapshotContent ready.

- changelogs/unreleased/100-jxun
- internal/util/util.go
- internal/util/util_test.go
Reverts vmware-tanzu/velero-plugin-for-csi#100
Fixes https://github.com/vmware-tanzu/velero/issues/4879
Move the waiting for ready logic into backup controller to let that process works parallel for multiple VolumeSnapshots.
> Revert "Add ReadyToUse status check before assuming VolumeSnapshotContent ready."

- internal/restore/pvc_action.go
Hi, the storage-provider annotation "volume.kubernetes.io/storage-provisioner" is now GA, so it is necessary to delete it on restore as well. I noticed it when I tested to backup/restore Longhorn PVs. This was not possible without this change.
related issue: https://github.com/kubernetes/kubernetes/issues/102357
> support GA storage-provider annotation

- internal/restore/pvc_action.go
- internal/restore/pvc_action_test.go
Consider doing a restore of a PVC that was created from a `dataSource`;
Since k8s 1.24, it will have both `dataSource` and `dataSourceRef` populated and equal: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#data-source-references
This becomes a problem in a "restore from an already restored PVC" scenario,
because we will carry over the older PVC's `dataSourceRef`, combined with the "new" `dataSource`, resulting in rejection.
Fixes https://github.com/vmware-tanzu/velero/issues/5404
Signed-off-by: Alex Kalenyuk <akalenyu@redhat.com>
> Fix: Restore of an already restored PVC

- changelogs/unreleased/126-blackpiglet
- internal/restore/pvc_action.go
- internal/restore/pvc_action_test.go
Fixes https://github.com/vmware-tanzu/velero/issues/5456
Consider doing a restore of a PVC that was created from a dataSource; Since k8s 1.24, it will have both dataSource and dataSourceRef populated and equal: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#data-source-references This becomes a problem here because we will carry over the older PVC's dataSourceRef, combined with the "new" dataSource, resulting in rejection.
Fixes https://github.com/vmware-tanzu/velero/issues/5404
Signed-off-by: Alex Kalenyuk <akalenyu@redhat.com>
> [Cherry-Pick][v0.3.2] cherry-pick PR #122 for v0.3.2

- .github/workflows/pr.yml
- .github/workflows/push.yml
- Makefile
- changelogs/unreleased/153-blackpiglet
Bump the Golang version to v1.19 for the GCP plugin's main branch.
> Bump the Golang version to v1.19 for the GCP plugin's main branch.

- internal/restore/pvc_action.go
Setting `DataSource` and `DataSourceRef` to a empty structure cannot work.
Restore fails with PartiallyFailed
```shell
error restoring persistentvolumeclaims/upgrade/my-pvc: PersistentVolumeClaim "my-pvc" is invalid: [spec.dataSource.name: Required value, spec.dataSource.kind: Required value, spec.dataSource: Invalid value: "", spec.dataSourceRef.name: Required value, spec.dataSourceRef.kind: Required value, spec.dataSourceRef: Invalid value: ""]
``` 
```go
pvc.Spec.DataSource = &corev1api.TypedLocalObjectReference{}
pvc.Spec.DataSourceRef = &corev1api.TypedLocalObjectReference{}
``` 
Failed to find this in verification, because the testing workload's PV is not a CSI one.
> Clean PVC's DataSource and DataSourceRef by setting them to nil.

- changelogs/unreleased/156-blackpiglet
- internal/restore/pvc_action.go
The PVC's data source and referenced volume should all be cleaned for restore to let k8s to create a new PV and volume.
> [cherry-pick][release-1.9]When restorePVs is false, CSI should restore the PVC.

- changelogs/unreleased/155-blackpiglet
- internal/restore/pvc_action.go
The PVC's data source and referenced volume should all be cleaned for restoration to let the k8s create a new PV and volume.
Fix https://github.com/vmware-tanzu/velero/issues/6074
> [cherry-pick][release-1.10]When restorePVs is false, CSI should restore the PVC.

- .github/workflows/pr.yml
- .github/workflows/push.yml
- Dockerfile
- Makefile
- README.md
- changelogs/unreleased/165-blackpiglet
- hack/docker-push.sh
- internal/restore/pvc_action.go
Unify the CSI plugin build process.
Bump the Golang version to v1.20.
Update the compatibility box in the README file.
Add pushing the image to gcr.io in action.
Modify  CI action trigger condition.
Fix https://github.com/vmware-tanzu/velero/issues/6146
> Unify CSI plugin build process and bump golang version.

- internal/util/util.go
- internal/util/util_test.go
When there's only one VolumeSnaphostClass that matches the provisoner, the plugin will choose it for snapshot disregarding whether it has the label or not.
Fixes https://github.com/vmware-tanzu/velero/issues/5833
> Update the logic to get VSClass for CSI snapshot

- internal/backup/volumesnapshot_action.go
- internal/util/util.go
Fix for the issue [Cleanup CSI Snapshots post Polling of VSC times out in CSI Plugin.]( https://github.com/vmware-tanzu/velero/issues/6219)
> Cleanup CSI Snapshots post Polling of VSC times out in CSI Plugin.

- go.mod
- go.sum
- internal/backup/pvc_action.go
- internal/backup/pvc_action_test.go
- internal/restore/pvc_action.go
- internal/restore/pvc_action_test.go
- internal/util/labels_annotations.go
Fix https://github.com/vmware-tanzu/velero/issues/6115
> Add snapshot data mover logic in PVC RIA v2.

- internal/backup/volumesnapshot_action.go
- internal/util/util.go
- internal/util/util_test.go
Here is a fix for the issue where CSISnapshotTimeout is not getting used by the plugin as reported here:
https://github.com/vmware-tanzu/velero/issues/6261
I ran these tests:
1. Edit snapshot-controller deployment to have 0 replicas so it would fail to create the snapshot.
Run a backup with CSISnapshotTimeout set to 1 minute and confirm from the log that timeout is honored.
2. Same test as above but without setting the CSISnapshotTimeout.  Timeout was 10 minutes as expected.
3. Let snapshot-controller deployment have 2 replicas and confirm that backup worked as normal.
4. Run "make test" and confirm that all tests passed.
> Use CSISnapshotTimeout to set the snapshot timeout

- internal/backup/pvc_action.go
- internal/backup/pvc_action_test.go
- internal/restore/pvc_action.go
- internal/restore/pvc_action_test.go
- internal/util/labels_annotations.go
* Limit label length to 63.
* Use the label const variables from the Velero repository.
* Add Velero resource usage label for DataUploadResult ConfigMap list query.
* Adjust UT accordingly.
> Limit the label "velero.io/pvc-namespace-name" length to 63.

- internal/restore/pvc_action.go
- internal/restore/pvc_action_test.go
Return PVC intact when CSI is not present in PVC spec to avoid deleting useful annotations: when backing up and restoring with FileSystem, and installing the Velero CSI plugin alongside, changing the PVC's node-selector by ConfigMap can trigger this issue.
> Return PVC intact when CSI is not present in PVC spec

- internal/restore/pvc_action.go
Fixes https://github.com/vmware-tanzu/velero/issues/6361
> Remove VS name annotation from PVC during CSI restore

- .gitignore
- internal/restore/pvc_action.go
- internal/restore/pvc_action_test.go
Fix conflict with #180.
Plugin workflow determines whether to restore depends on PVC has the VolumeSnapshot annotation, so change to check the annotation from the pvcFromBackup, not the modified PVC.
> Resolve conflict with PR #180

- internal/backup/pvc_action.go
- internal/util/labels_annotations.go
This is needed for notifying the velero process about the reason the PV was skipped.
> Annotate the PVC for non CSI PV

- internal/restore/pvc_action.go
- internal/restore/volumesnapshot_action.go
- internal/util/util.go
- internal/util/util_test.go
do not change the namespace of pvc and vs in restore plugin directly, because:
1. namespace is updated in velero resore process after all RIAs are finished
2. If the namespace is changed in a RIA, all the following RIAs will be affacted.
> do not change the namespace of pvc and vs in restore plugin directly

- .github/workflows/push.yml
- internal/restore/pvc_action.go
Fix issue https://github.com/vmware-tanzu/velero/issues/6819
> Use backup.Spec.CSISnapshotTimeout for DataDownload OperationTimeout

- .github/workflows/push.yml
- internal/restore/pvc_action.go
Use backup.Spec.CSISnapshotTimeout for DataDownload OperationTimeout. Remove not needed pushing to GCR action.
> [cherry-pick][release-0.6]Use backup.Spec.CSISnapshotTimeout for DataDownload OperationTimeout.

- internal/util/util.go
Improved error floatation during csi-polling timeout scenario.
> Fix Error log bug

- go.mod
- go.sum
Signed-off-by: Tiger Kaovilai <tkaovila@redhat.com>
> release-0.6: CVE-2023-44487 gRPC-Go HTTP/2 Rapid Reset vulnerability

- go.mod
- go.sum
- internal/backup/pvc_action.go
- internal/restore/pvc_action.go
Replace some const variables definination with references from Velero.
> Bump Velero version.

- internal/util/util.go
CSI plugin panics on nil pointer when csiSnapshotTimeout is set to a short duration.
for example when csiSnapshotTimeout: 0m1s, we get:
`time="2023-11-13T09:22:01Z" level=error msg="Error backing up item" backup=openshift-adp/b13 error="error executing custom action (groupResource=persistentvolumeclaims, namespace=a1, name=mysql-1): rpc error: code = Aborted desc = plugin panicked: runtime error: invalid memory address or nil pointer dereference, stack trace: goroutine 116 [running]:\nruntime/debug.Stack()\n\t/usr/lib/golang/src/runtime/debug/stack.go:24 +0x65\ngithub.com/vmware-tanzu/velero/pkg/plugin/framework/common.HandlePanic({0x1f127e0, 0x3736c90})\n\t/remote-source/deps/gomod/pkg/mod/github.com/vmware-tanzu/velero@v1.12.0/pkg/plugin/framework/common/handle_panic.go:43 …
> Fix panic when csi timeout duration is short

- internal/backup/pvc_action.go
- internal/backup/pvc_action_test.go
- internal/backup/volumesnapshot_action.go
- internal/backup/volumesnapshotcontent_action.go
- internal/restore/pvc_action.go
- internal/restore/pvc_action_test.go
- internal/util/util.go
* Only generate one Async Operation for CSI backup.
* use function passed-in context.
* replace the deprecated `apimachinery/pkg/util/wait` method and variable.
* remove unneeded function parameters.
> Only generate one Async Operation for CSI backup and some code refactor

- internal/backup/volumesnapshot_action.go
This PR is part of https://github.com/vmware-tanzu/velero/pull/7554.
It set the VolumeSnapshot async operation's `Status.Updated` when the operation completes.
> Set operation progress update time for VS BIA on completion.

- README.md
As I was investigating a broken Velero setup (mistakenly updated by Renovate), I had to remove it from my configuration. Clarifying this on this project readme could help others realize the origin of the problem faster.
> docs(readme): Add a note that this plugin has been merged to Velero  v1.14
